#!/usr/bin/env bash
set -euo pipefail

cd /home/opc/charon

if [ ! -f /home/opc/charon/.env ]; then
  echo "[charon] /home/opc/charon/.env is missing; refusing to start. Create it from .env.operator.example." >&2
  exit 64
fi

# Preserve PM2/runtime instance overrides before sourcing .env. The .env file
# provides credentials; PM2 owns per-process identity and DB isolation.
PM2_INSTANCE_ID="${INSTANCE_ID:-}"
PM2_SHADOW_MODE="${SHADOW_MODE:-}"
PM2_LIVE_EXECUTION_DISABLED="${LIVE_EXECUTION_DISABLED:-}"
PM2_DB_PATH="${DB_PATH:-}"
PM2_HARVESTER_DB_PATH="${HARVESTER_DB_PATH:-}"
PM2_TRADING_MODE="${TRADING_MODE:-}"
PM2_TELEGRAM_POLLING_ENABLED="${TELEGRAM_POLLING_ENABLED:-}"
PM2_LLM_BASE_URL="${LLM_BASE_URL:-}"
PM2_LLM_MODEL="${LLM_MODEL:-}"
PM2_LLM_API_KEY="${LLM_API_KEY:-}"
PM2_LLM_PROVIDER_ORDER="${LLM_PROVIDER_ORDER:-}"
PM2_LLM_REASONING_EFFORT="${LLM_REASONING_EFFORT:-}"
PM2_MIMO_LLM_BASE_URL="${MIMO_LLM_BASE_URL:-}"
PM2_MIMO_LLM_MODEL="${MIMO_LLM_MODEL:-}"
PM2_MIMO_LLM_API_KEY="${MIMO_LLM_API_KEY:-}"
PM2_GROQ_LLM_BASE_URL="${GROQ_LLM_BASE_URL:-}"
PM2_GROQ_LLM_MODEL="${GROQ_LLM_MODEL:-}"
PM2_GROQ_LLM_API_KEY="${GROQ_LLM_API_KEY:-}"
PM2_MISTRAL_LLM_BASE_URL="${MISTRAL_LLM_BASE_URL:-}"
PM2_MISTRAL_LLM_MODEL="${MISTRAL_LLM_MODEL:-}"
PM2_MISTRAL_LLM_API_KEY="${MISTRAL_LLM_API_KEY:-}"
PM2_GEMINI_LLM_BASE_URL="${GEMINI_LLM_BASE_URL:-}"
PM2_GEMINI_LLM_MODEL="${GEMINI_LLM_MODEL:-}"
PM2_GEMINI_LLM_API_KEY="${GEMINI_LLM_API_KEY:-}"
PM2_SHADOW_LLM_BASE_URL="${SHADOW_LLM_BASE_URL:-}"
PM2_SHADOW_LLM_MODEL="${SHADOW_LLM_MODEL:-}"
PM2_SHADOW_LLM_API_KEY="${SHADOW_LLM_API_KEY:-}"
PM2_SHADOW_LLM_REASONING_EFFORT="${SHADOW_LLM_REASONING_EFFORT:-}"
PM2_SCOUT_LLM_THROTTLE_ENABLED="${SCOUT_LLM_THROTTLE_ENABLED:-}"
PM2_SCOUT_LLM_MINT_COOLDOWN_MS="${SCOUT_LLM_MINT_COOLDOWN_MS:-}"
PM2_SCOUT_LLM_HOURLY_CAP="${SCOUT_LLM_HOURLY_CAP:-}"
PM2_SCOUT_LLM_DAILY_CAP="${SCOUT_LLM_DAILY_CAP:-}"
PM2_SCOUT_LLM_PRE_SCORE_THRESHOLD="${SCOUT_LLM_PRE_SCORE_THRESHOLD:-}"
PM2_SCOUT_LLM_HIGH_SCORE_RESERVE_THRESHOLD="${SCOUT_LLM_HIGH_SCORE_RESERVE_THRESHOLD:-}"
PM2_SCOUT_LIVE_ENABLED="${SCOUT_LIVE_ENABLED:-}"
PM2_SCOUT_POLICY_ENABLED="${SCOUT_POLICY_ENABLED:-}"
PM2_SCOUT_POLICY_ACTIVE_VERSION="${SCOUT_POLICY_ACTIVE_VERSION:-}"
PM2_SCOUT_DAILY_BUY_CAP="${SCOUT_DAILY_BUY_CAP:-}"
PM2_SCOUT_DAILY_LOSS_STOP_SOL="${SCOUT_DAILY_LOSS_STOP_SOL:-}"
PM2_MAX_OPEN_POSITIONS="${MAX_OPEN_POSITIONS:-}"
PM2_GLOBAL_LIVE_LOCK_DB_PATH="${GLOBAL_LIVE_LOCK_DB_PATH:-}"
PM2_GLOBAL_LIVE_LOCK_ENABLED="${GLOBAL_LIVE_LOCK_ENABLED:-}"
PM2_GLOBAL_LIVE_LOCK_MAX_OPEN_SOL="${GLOBAL_LIVE_LOCK_MAX_OPEN_SOL:-}"

set -a
. /home/opc/charon/.env
set +a

export CHARON_SKIP_DOTENV="true"

export INSTANCE_ID="${PM2_INSTANCE_ID:-${INSTANCE_ID:-primary}}"
export SHADOW_MODE="${PM2_SHADOW_MODE:-${SHADOW_MODE:-false}}"
export LIVE_EXECUTION_DISABLED="${PM2_LIVE_EXECUTION_DISABLED:-${LIVE_EXECUTION_DISABLED:-false}}"
export DB_PATH="${PM2_DB_PATH:-${DB_PATH:-/opt/trading-data/charon.sqlite}}"
export HARVESTER_DB_PATH="${PM2_HARVESTER_DB_PATH:-${HARVESTER_DB_PATH:-/opt/trading-data/harvester.db}}"
export TRADING_MODE="${PM2_TRADING_MODE:-${TRADING_MODE:-dry_run}}"
export TELEGRAM_POLLING_ENABLED="${PM2_TELEGRAM_POLLING_ENABLED:-${TELEGRAM_POLLING_ENABLED:-true}}"
export LLM_BASE_URL="${PM2_LLM_BASE_URL:-${LLM_BASE_URL:-}}"
export LLM_MODEL="${PM2_LLM_MODEL:-${LLM_MODEL:-}}"
export LLM_API_KEY="${PM2_LLM_API_KEY:-${LLM_API_KEY:-}}"
export LLM_PROVIDER_ORDER="${PM2_LLM_PROVIDER_ORDER:-${LLM_PROVIDER_ORDER:-}}"
export LLM_REASONING_EFFORT="${PM2_LLM_REASONING_EFFORT:-${LLM_REASONING_EFFORT:-}}"
export MIMO_LLM_BASE_URL="${PM2_MIMO_LLM_BASE_URL:-${MIMO_LLM_BASE_URL:-}}"
export MIMO_LLM_MODEL="${PM2_MIMO_LLM_MODEL:-${MIMO_LLM_MODEL:-}}"
export MIMO_LLM_API_KEY="${PM2_MIMO_LLM_API_KEY:-${MIMO_LLM_API_KEY:-}}"
export GROQ_LLM_BASE_URL="${PM2_GROQ_LLM_BASE_URL:-${GROQ_LLM_BASE_URL:-}}"
export GROQ_LLM_MODEL="${PM2_GROQ_LLM_MODEL:-${GROQ_LLM_MODEL:-}}"
export GROQ_LLM_API_KEY="${PM2_GROQ_LLM_API_KEY:-${GROQ_LLM_API_KEY:-}}"
export MISTRAL_LLM_BASE_URL="${PM2_MISTRAL_LLM_BASE_URL:-${MISTRAL_LLM_BASE_URL:-}}"
export MISTRAL_LLM_MODEL="${PM2_MISTRAL_LLM_MODEL:-${MISTRAL_LLM_MODEL:-}}"
export MISTRAL_LLM_API_KEY="${PM2_MISTRAL_LLM_API_KEY:-${MISTRAL_LLM_API_KEY:-}}"
export GEMINI_LLM_BASE_URL="${PM2_GEMINI_LLM_BASE_URL:-${GEMINI_LLM_BASE_URL:-}}"
export GEMINI_LLM_MODEL="${PM2_GEMINI_LLM_MODEL:-${GEMINI_LLM_MODEL:-}}"
export GEMINI_LLM_API_KEY="${PM2_GEMINI_LLM_API_KEY:-${GEMINI_LLM_API_KEY:-}}"
export SHADOW_LLM_BASE_URL="${PM2_SHADOW_LLM_BASE_URL:-${SHADOW_LLM_BASE_URL:-}}"
export SHADOW_LLM_MODEL="${PM2_SHADOW_LLM_MODEL:-${SHADOW_LLM_MODEL:-}}"
export SHADOW_LLM_API_KEY="${PM2_SHADOW_LLM_API_KEY:-${SHADOW_LLM_API_KEY:-}}"
export SHADOW_LLM_REASONING_EFFORT="${PM2_SHADOW_LLM_REASONING_EFFORT:-${SHADOW_LLM_REASONING_EFFORT:-}}"
export SCOUT_LLM_THROTTLE_ENABLED="${PM2_SCOUT_LLM_THROTTLE_ENABLED:-${SCOUT_LLM_THROTTLE_ENABLED:-}}"
export SCOUT_LLM_MINT_COOLDOWN_MS="${PM2_SCOUT_LLM_MINT_COOLDOWN_MS:-${SCOUT_LLM_MINT_COOLDOWN_MS:-}}"
export SCOUT_LLM_HOURLY_CAP="${PM2_SCOUT_LLM_HOURLY_CAP:-${SCOUT_LLM_HOURLY_CAP:-}}"
export SCOUT_LLM_DAILY_CAP="${PM2_SCOUT_LLM_DAILY_CAP:-${SCOUT_LLM_DAILY_CAP:-}}"
export SCOUT_LLM_PRE_SCORE_THRESHOLD="${PM2_SCOUT_LLM_PRE_SCORE_THRESHOLD:-${SCOUT_LLM_PRE_SCORE_THRESHOLD:-}}"
export SCOUT_LLM_HIGH_SCORE_RESERVE_THRESHOLD="${PM2_SCOUT_LLM_HIGH_SCORE_RESERVE_THRESHOLD:-${SCOUT_LLM_HIGH_SCORE_RESERVE_THRESHOLD:-}}"
export SCOUT_LIVE_ENABLED="${PM2_SCOUT_LIVE_ENABLED:-${SCOUT_LIVE_ENABLED:-}}"
export SCOUT_POLICY_ENABLED="${PM2_SCOUT_POLICY_ENABLED:-${SCOUT_POLICY_ENABLED:-}}"
export SCOUT_POLICY_ACTIVE_VERSION="${PM2_SCOUT_POLICY_ACTIVE_VERSION:-${SCOUT_POLICY_ACTIVE_VERSION:-}}"
export SCOUT_DAILY_BUY_CAP="${PM2_SCOUT_DAILY_BUY_CAP:-${SCOUT_DAILY_BUY_CAP:-}}"
export SCOUT_DAILY_LOSS_STOP_SOL="${PM2_SCOUT_DAILY_LOSS_STOP_SOL:-${SCOUT_DAILY_LOSS_STOP_SOL:-}}"
export MAX_OPEN_POSITIONS="${PM2_MAX_OPEN_POSITIONS:-${MAX_OPEN_POSITIONS:-}}"
export GLOBAL_LIVE_LOCK_DB_PATH="${PM2_GLOBAL_LIVE_LOCK_DB_PATH:-${GLOBAL_LIVE_LOCK_DB_PATH:-}}"
export GLOBAL_LIVE_LOCK_ENABLED="${PM2_GLOBAL_LIVE_LOCK_ENABLED:-${GLOBAL_LIVE_LOCK_ENABLED:-}}"
export GLOBAL_LIVE_LOCK_MAX_OPEN_SOL="${PM2_GLOBAL_LIVE_LOCK_MAX_OPEN_SOL:-${GLOBAL_LIVE_LOCK_MAX_OPEN_SOL:-}}"

if [ "$SHADOW_MODE" = "true" ]; then
  export LIVE_EXECUTION_DISABLED="true"
  export TRADING_MODE="dry_run"
  export TELEGRAM_POLLING_ENABLED="false"
  export LLM_PROVIDER_ORDER="${PM2_LLM_PROVIDER_ORDER:-legacy,cliproxy}"
  unset SOLANA_PRIVATE_KEY
  unset PRIVATE_KEY
fi

if [ "$TRADING_MODE" != "dry_run" ]; then
  echo "[charon] TRADING_MODE=$TRADING_MODE; refusing PM2 bot start unless TRADING_MODE=dry_run." >&2
  exit 65
fi

for required in TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID; do
  if [ -z "${!required:-}" ]; then
    echo "[charon] $required is missing; refusing to start." >&2
    exit 66
  fi
done

if [ -z "${HELIUS_API_KEY:-}" ] && { [ -z "${SOLANA_RPC_URL:-}" ] || [ -z "${SOLANA_WS_URL:-}" ]; }; then
  echo "[charon] HELIUS_API_KEY or both SOLANA_RPC_URL/SOLANA_WS_URL are required; refusing to start." >&2
  exit 67
fi

exec /usr/bin/node index.js
